name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Tuesday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Bhargav it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Sai Bhargav V
